[package]
name = "warframe_market"
version = "0.2.0"
edition = "2024"

[dependencies]
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["macros"] }
